### ISSUE TITLE
Fix moment deprecation warning

### ISSUE THREAD

**Issue by roest01** [roest01/docker-speedtest-analyser#2]
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Arguments: [object Object]

`Error
    at Function.createFromInputFallback (http://speedtest.nas:8085/js/libs/moment-with-locales.min.js:1:8139)
    at Ca (http://speedtest.nas:8085/js/libs/moment-with-locales.min.js:1:12814)
    at Ba (http://speedtest.nas:8085/js/libs/moment-with-locales.min.js:1:12548)
    at Aa (http://speedtest.nas:8085/js/libs/moment-with-locales.min.js:1:12268)
    at Da (http://speedtest.nas:8085/js/libs/moment-with-locales.min.js:1:12991)
    at Ea (http://speedtest.nas:8085/js/libs/moment-with-locales.min.js:1:13025)
    at o.fb [as isAfter] (http://speedtest.nas:8085/js/libs/moment-with-locales.min.js:1:17378)
    at DateRangePicker.renderTimePicker (http://speedtest.nas:8085/js/libs/daterangepicker.js:871:34)
    at DateRangePicker.updateView (http://speedtest.nas:8085/js/libs/daterangepicker.js:506:22)
    at DateRangePicker.hoverRange (http://speedtest.nas:8085/js/libs/daterangepicker.js:1164:22)
ea @ moment-with-locales.min.js:1
`

Would be fixed by updating the dangrossman/bootstrap-daterangepicker dep.

**Comment by ShagoY** [comment]
Hi Roest01, I have "invalid date" too. Your container is over ?

**Comment by roest01** [comment]
Hey ShagoY,
The container is still maintained. I still have an instance running.
This deprications warning is not a blocker but nice2have. There should be no impact?

From my experience i can say the startup can be optimised. 
Be sure to have at least two data rows in the datebase file.

It would be glad if you find and report any bugs or/and make a PR to solve them.

**Comment by roest01** [comment]
Fixed that warning by updating deps
